echo "\n============ SCANNING ============="
echo "============= SCAN COMPLETE =========="
echo "\\n ========= SCANNING SSN =========="
echo "============= SCAN COMPLETE ========="
echo "\\n ========= SCANNING PHONES ======="
echo "============= SCAN COMPLETE ========="
